### ISSUE TITLE
We Want Mor + Audiobook feed skips chapter 32

### ISSUE THREAD

**Issue by Kynake** [GorkyR/Custom-Podcast-Feeds#1]
As mentioned in the title, chapter 32 (Xmas Interlude: Personal Financial Management) is missing from the combined feed.

**Comment by Kynake** [comment]
Seems like there should be an entry right between these episodes:
https://github.com/GorkyR/Custom-Podcast-Feeds/blob/803306c1e9b298d94999364a5359e4aa34746a00/we-want-mor-audiobook.rss#L754-L791

**Comment by GorkyR** [comment]
You're right.  It is included now.  Thanks!
